### ISSUE TITLE
Associations should default to `required = false`

### ISSUE THREAD

**Issue by idris** [mickhansen/graphql-sequelize#239]
When generating the query for associations, `generateIncludes` should default to using `required = false` so that it does a `LEFT OUTER JOIN` instead of `INNER JOIN`

Because it's defaulted to `INNER JOIN`, I ran into a weird situation where if I queried for _more_ fields (a hasOne relationship), it returned less rows.  That's very counter-intuitive, so I think the default should be changed.

**Comment by mickhansen** [comment]
It should be changed.
In general i'm looking to move away from prefetching for this library, the independent/hierarchical nature of graphql does not benefit greatly from prefetching / joins.
I'm working on making Sequelize more batch friendly and in the future graphql-sequelize will be refactored to rely on batching rather than prefetching.

**Comment by brad-decker** [comment]
@mickhansen if you need help with this endeavor i'd love to jump in. Sounds like the right approach from what I gathered at react europe.

**Comment by mickhansen** [comment]
@brad-decker Sure :)
But yes definitely, prefetching is actually sort of a bad solution to graphql - In the future i'll implement batching instead.
