### ISSUE TITLE
node query fetches all columns

### ISSUE THREAD

**Issue by nikhildaga** [mickhansen/graphql-sequelize#295]
When I query through node field, all the columns are fetched.

e.g. in the following code, sequelize queries all the columns in user

```
 node(id: "aW5kdXN0cnk6") {
    id,
    ... on user{
      name
    }
  }

```

while the following code works perfectly and fetches only id and name

```
{
  data {
    users {
      id
      ... on user{
        name
      }
    }
  }
}
```

Is this expected?

**Comment by mickhansen** [comment]
It's expected: https://github.com/mickhansen/graphql-sequelize/blob/master/src/relay.js#L54
Expect filterAttributes to be removed from future versions in any case since it just causes headaches.

Performance impact is only present if fetching larger blobs, so these can be filtered out by user via `before()`

**Comment by nikhildaga** [comment]
Thanks Mick! I am a big fan of your projects.

> Expect filterAttributes to be removed from future versions in any case since it just causes headaches.

That's sad. filterAttributes (by this I believe you mean, fetching only the selected columns in query ) is one of the main reasons I use this module. Please don't remove it. Defaulting it to false instead of true is also an option. 

Won't selecting all columns every time be bad for performance? I think you must have thought of some better solution.

**Comment by mickhansen** [comment]
The performance impact is negligible unless you have larger BLOB/TEXT columns.
Defaulting to false is an option, it also means less coverage.
The primary issue with the feature is that it conflicts with the general philosophy of GraphQL and how this project will handle things moving forward (batching and post-fetching rather than pre-fetching).

**Comment by shakaIsReal** [comment]
@mickhansen  That kind of sucks... What if user wants to get 10 comments from a post? 
Right now we are fetching unnecessarily information on the parent type (in our case `PostType`) just to get the comments.

Relay makes a query like this: 

```
{
node(id: 'base64) {                      // base64 string (id + type)
  id    //  PostType id  
     comments(first:10, after: 'base64') { 
       text 
       user { name }
     }
 }
}
```

We only really want the `id`, we could return it. However this goes against relay infrastructure where you can do `this.props.relay.forceFetch()`. 

Do you suggest creating a separate query? 
For example: 
```
{ 
 loadMoreComments { 
   type: Comments, 
  resolve: resolver(...) 
}
}
```
But this means that we can't leverage `this.props.relay.setVariables()` which would make a query to the server automatically. Therefore custom logic should be implemented. 

I also believe that batching and caching is the best option. Since it gives the ability to fetch fields that the client really asked for. But right now I haven't found a solution or any example for implementing this with dataloader. Do you have any advice/resources on this topic?

**Comment by mickhansen** [comment]
@shakaIsReal You'll have to make up your mind, you can't use attribute filtering AND batching/caching effectively.

I've had no problems with Relay using non-attribute filtering batching, `setVariables` works just fine.

I highly doubt fetching a few more fields from a RDBMS is the primary performance concern of your graphql queries.

**Comment by shakaIsReal** [comment]
Thanks, could please give a rough idea on how to use dataloader inside fields in graphql. As I understand I need one dataloader for each type and use it in every field that needs to be batched into one query. For example: 

```
name {
type: GraphQLString, 
resolve: (_, args) => DataLoader(['name', args.id]).then((data) => data)
},
email: { 
type: GraphQLString, 
resolve: (_, args) => DataLoader(['email', args.id]).then((data) => data)
}
```
Where `DataLoader` would return `SELECT name, email FROM users WHERE id = 1`

**Comment by mickhansen** [comment]
I don't think you would use data loader for simple primitives, i'd use data loader on the parent type.
We do internally use data loader for some fields which depend on externals.

**Comment by shakaIsReal** [comment]
>  i'd use data loader on the parent type 
Do you mean using it in the query, before data gets to the type? If so, I don't understand how is this different from pre-fetch processing (as I mentioned earlier)

**Comment by mickhansen** [comment]
I suppose so, i don't know your setup, we use it on stuff like `user(id: "globalId")`.
pre-fetch processing doesn't lend well to batching or catching, but it's really up to you what trade off you want, i can't help you decide that.

**Comment by shakaIsReal** [comment]
Cool thanks 👍
