### ISSUE TITLE
Extending the default args to allow includes

### ISSUE THREAD

**Issue by tnrich** [mickhansen/graphql-sequelize#471]
Hey there,

Thanks for your awesome repo. I've been using it so far via `graphql-sequelize-crud` and am liking how it sets up most things I need automagically. It appears to use your `defaultListArgs` function under the hood. 

One thing I can't figure out how to do with it is to make a query that makes a sequelize "includes" call on an associated model. 

 For example, if I want to query my Projects for a given search string. I can use the where argument to search the todo fields. 
```
Project.findAll({
    where: {  // where is supported out of the box
        "status": {
            "like": "%bla%"
         },
    }
})
```
But, searching on the associated owner name doesn't seem possible:

```
Project.findAll({
    include: [{  //include is not supported
        model: User,
        where: {
            "status": {
                "like": "%bla%"
             },
        }
    }]
})
```

Do you know how I can support this type of call to sequelize? Should I just try to extend the default args to accept an "include" type as well?

Any guidance/help would be greatly appreciated. Thanks!

**Comment by mickhansen** [comment]
I'm not sure i follow, you want the client to be able to define what includes to make? That should be known implicitely from the requested fields.

**Comment by tnrich** [comment]
Hey @mickhansen, thanks for getting back to me. Let me try to explain more clearly:
Here is the query I'm making to filter a list of materials (searching all possible fields for the string "a"):
```
query ($limit: Int, $order: String, $where: SequelizeJSON, $offset: Int) {
  materials(limit: $limit, order: $order, where: $where, offset: $offset) {
    id
    status
    sourceSystem
    type
    name
    createdAt
    updatedAt
    user {
      id
      fullName
      __typename
    }
    __typename
  }
}
```
with variables:
```
{
  "limit": 15,
  "order": "",
  "where": {
    "$or": {
      "status": {
        "like": "%a%"
      },
      "sourceSystem": {
        "like": "%a%"
      },
      "type": {
        "like": "%a%"
      },
      "name": {
        "like": "%a%"
      },
      
    }
  },
  "offset": 0
}
```

Now, all that is working great, but, I also want to filter on the user.fullName. I'm not sure how I can do this using graphql-sequelize/graph-ql-sequelize crud. I can't pass variables to my nested "user" query. Nor does the top-level query "where:" support filtering on nested data (at least I don't think). 

So, is there a way to filter on the user.fullName? 

Thank you very much for your help! Keep up the good work!

**Comment by Alexsey** [comment]
@tnrich I have met the same problem. But according to how `graphql-sequelize` works now - this is not possible because to do that (effectively) you need to load all your data with `INNER JOIN` inside a single SQL request. But `graphql-sequelize` uses [`dataloader-sequelize`](https://github.com/mickhansen/dataloader-sequelize) and loads each "data layer" separately and sequentially: first it will loads your `materials` and only then it will loads `material`'s `user`s with filters you add to them. So even if `graphql-sequelize` would let you use `include` in `where` you will load your `user`s in a separate request and your `users` table will be requested twice: first time with `JOIN` on `materials` and second time individually

And even if `graphql-sequelize` moves to `JOIN` strategy - there will be no sense of letting you do the `include` in `where` - it would be correct to construct that `include`s for you inside the `graphql-sequelize` while you will add your filters separately for `materials` and `user` (like it is now). But in this case you will face the bugs of `sequelize` itself like https://github.com/sequelize/sequelize/issues/7344 or https://github.com/sequelize/sequelize/issues/7852. And while you work with `sequelize` you always have an option to write raw SQL to pass through, in `graphql-sequelize` there would be no way to handle them

@mickhansen am I right? I would really like to know your thinking about that

**Comment by mickhansen** [comment]
@tnrich Subqueries is generally the best way to solve that, SQL includes dont really behave well together with graphql

**Comment by Alexsey** [comment]
I have already add support for this in my code. Will create a PR after write some tests and docs. This will happened at the beginning of this week or in the first days of the next week
