### ISSUE TITLE
Use more readable SDL and declare resolvers apart in the documentation

### ISSUE THREAD

**Issue by hendrul** [mickhansen/graphql-sequelize#565]
The documentation example could be far more readable if you define the schema in the graphql Schema definition language and create the resolvers object in other step.

**Comment by intellix** [comment]
Came here to create a similar issue. It seems consistently recommended throughout the GQL world to now define types via SDL and Resolvers separately. I think I saw @mickhansen echo something that he doesn't recommend the `attributeFields()` helper anymore because of it. 

Guess someone just to replace the examples in the README with a PR that shows it like this

**Comment by mickhansen** [comment]
The primary reason i don't recommend `attributeFields` is that it makes schema generation kind of magic, which i dislike. Using SDL is probably the most anti magic you can get so that's definitely a good idea, although i have personally not yet made the transistion.
