### ISSUE TITLE
how to eagerly load an associated model when using resolver without include?

### ISSUE THREAD

**Issue by tomprogers** [mickhansen/graphql-sequelize#574]
I want to do this:

```
driver: {
    type: MyGQLTypes.Driver,
    resolve: resolver(Driver, {
        include: { model: Helmet }
    })
}
```

But `include` is now disallowed. What's the workaround?

[Related stackoverflow](https://stackoverflow.com/questions/49329950/how-am-i-supposed-to-eagerly-load-an-association-using-graphql-sequelize-without).

**Comment by mickhansen** [comment]
include never worked like that, it was/is a boolean option that tried to predict what kind of relations you would want based on the subfields in the query.

You can add includes manually in the before hook if you absolutely need to (if it's a 1:M you almost always use for instance), but otherwise stick to using dataloader logic, the performance is more linear and predictable than includes are.

**Comment by RoelRoel** [comment]
How to use dataloader logic?

I got this mutation where I need the organisation of the user. How to load it. Why isn't it lazy loaded when I call the user.organisation property?

forgetPassword: resolver(User, { include: [Organisation],
        before: async (findOptions, { email }) => {
            findOptions.where = { email };
            return findOptions;
        }, [..]
